# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9163723cd41c1fba48c4b30556db0b64628c891a8d2ae022333b522d6ba7441e4a6200d2bae98fe66b3d1cbdfdca2950bb8d45dd7ace6c2c9deba6740bf841a

test:
  secret_key_base: d3e420687a0cc70d38a99501bd632482f9724dc42490eb504915640e60475f8a2d760578300b7d42a1ad89039469bc473d11759968c04a5491689bdc990e0863

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
